name: "Allocate Security Identifiers"
on: 
  workflow_dispatch:
    branches:
      - main
  schedule:
    - cron: '27 5 * * MON-FRI'

concurrency:
  group: allocate-security-identifiers
  cancel-in-progress: true

permissions: {}

jobs:
  allocate-security-identifiers:
    name: "Allocate Security Identifiers"
    runs-on: runs-on=${{ github.run_id }}/runner=medium-arm
    container:
      image: python:3.14-alpine
    permissions:
      contents: write
    if: github.repository == 'anchore/security-identifiers' # only run for main repo
    steps:
      - name: Install OS dependencies
        run: apk add --no-cache git openssh taplo sqlite tar zstd curl oras-cli bash date grype
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install python dependencies
        run: pip install git+https://github.com/anchore/security-cli
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: true
      - name: Allocate security identifiers
        run: anchore-security-cli id allocate --data-path data
      - name: Run TOML formatting
        run: taplo format
      - name: Run TOML schema validation
        run: taplo validate --schema file:${PWD}/schema/0.1.0.schema.json
      - name: Run TOML formatting validation
        run: taplo format --check
      - name: Commit changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          ./scripts/commit.sh
          git push
